services:
  backend:
    image: fm39hz/library:latest
    container_name: backend
    networks:
      - library_service
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mariadb://mariadb:3306/library"
      SPRING_DATASOURCE_USERNAME: "library"
      SPRING_DATASOURCE_PASSWORD: "@VeryStr1ctP@ssvvord"
    depends_on:
      - database

  database:
    image: mariadb:latest
    container_name: mariadb
    networks:
      - library_service
    ports:
      - "3309:3306"
    environment:
      MARIADB_ROOT_PASSWORD: "@VeryStr1ctP@ssvvord"
      MARIADB_DATABASE: "library"
      MARIADB_USER: "library"
      MARIADB_PASSWORD: "@VeryStr1ctP@ssvvord"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d

networks:
  library_service:
volumes:
  mariadb_data:
